[registries]
universe = { index = "sparse+https://rust.pkg.re/universe/" }
pkgre = { index = "sparse+https://rust.pkg.re/pkgre/" }

[registry]
default = "universe"

[source.crates-io]
replace-with = "disabled-crates-io"

[source.disabled-crates-io]
directory = "vendor/empty"
